{"metadata":{"symbolKind":"case","title":"IScribeAI.ClientAuthenticationError.internalError(description:)","modules":[{"name":"IScribeAISDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"externalID":"s:12IScribeAISDK0A2AIC25ClientAuthenticationErrorO08internalF0yAESS_tcAEmF","roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time."}],"hierarchy":{"paths":[["doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError"]]},"variants":[{"paths":["\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","interfaceLanguage":"swift"},"references":{"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI":{"navigatorTitle":[{"kind":"identifier","text":"IScribeAI"}],"title":"IScribeAI","role":"symbol","abstract":[{"text":"This singleton is the primary interaction point for clients of the SDK. It handles starting and stopping recording as well as submitting recordings for processing and iScribe AI summary generation.","type":"text"}],"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","url":"\/documentation\/iscribeaisdk\/iscribeai","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IScribeAI","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError":{"type":"topic","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError","abstract":[{"text":"An error that may occur while attempting to authenticate the provided JWT token.","type":"text"}],"title":"IScribeAI.ClientAuthenticationError","navigatorTitle":[{"kind":"identifier","text":"ClientAuthenticationError"}],"url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientAuthenticationError","kind":"identifier"}],"kind":"symbol"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError/internalError(description:)":{"title":"IScribeAI.ClientAuthenticationError.internalError(description:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","type":"topic","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)","abstract":[{"type":"text","text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time."}]},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK":{"title":"IScribeAISDK","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","url":"\/documentation\/iscribeaisdk","kind":"symbol","type":"topic","role":"collection","abstract":[{"text":"iScribe AI eliminates the burden of medical documentation, giving providers back time and energy to reinvest in their patients and their own wellbeing.","type":"text"},{"type":"text","text":" "},{"text":"This iOS SDK provides direct access to the iScribe AI service. Simply record audio for a providerâ€™s session with a patient and submit. Our service will then auto-generate high quality medical documentation based on the content of that recording.","type":"text"}]}}}